spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://1.117.165.232:3306/campus-callback
    username: campus-callback
    password: jmwaN2537yzResJZ